name: aerospike-tools.docker

container:
  - base:
#       - docker.qe.aerospike.com/build/aerospike-tools.docker:latest
    - docker.qe.aerospike.com/build/aerospike-tools-alt:ubuntu-16.04

build:
  - name: default
    environment:
      DOCKER_BUILDKIT: 1
    script:
      - sleep 120
#       - cd /work/source/
#       - docker build -t docker.qe.aerospike.com/aerospike/aerospike-tools .
#       - docker push docker.qe.aerospike.com/aerospike/aerospike-tools

qe-registry:
  - dockerfile: /work/source/Dockerfile
  - tag:  docker.qe.aerospike.com/aerospike/aerospike-tools
