name: aerospike-tools.docker

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-tools.docker:latest

build:
  - name: default
    environment:
      DOCKER_BUILDKIT: 1
    script:
      - ls
    artifact:
      - /work/
qe-registry:
  - dockerfile: /work/source/Dockerfile
  - registry:  docker.qe.aerospike.com/aerospike/aerospike-tools
